### PR TITLE
Player accessibility improvements.

### LINKED ISSUE #41: Player accessibility improvements.
- ~~An element exists in the DOM which contains keyboard use instructions, but it is not reachable in the tab order.~~
  - ~~It's easy enough to add this element to the tab order, but for users who have to use a keyboard but do not use a screen reader it ends up being a mysterious invisible extra tab stop.~~
    - Replace this always-invisible element with something that is only visible when it has focus and shows/hides a dialog window with the keyboard instructions. Sighted keyboard users can activate the element like a button to bring up a dialog window with keyboard instructions, and we can aria-label the element with the full instructions for unsighted users so they can tab past it without needing to open the dialog.

- ~~It's possible to tab out of an active question because the header and game board are still rendered and still in the tab order.~~
  - ~~Either make everything outside of the question popup unreachable by tab, or opt not to render them at all while there's a current question.~~
    - ~~This might be problematic since it looks like the questions still being tab-available is what's allowing the focus to be returned to the game board after a question popup is dismissed.~~
  - This can be handled by setting a value for the `inert` attribute on the header and game board elements when a question is selected, then removing that attribute from those elements when a question is cleared. This requires that the `id="checkAns"` element being read by screen readers immediately upon answering a question must be moved out of the header to remain visible while the header is inert.

- ~~The question text is not reachable in the tab order, so it's only read once to screen readers and can not be repeated.~~
  - This is resolved by adding the question text to the tab order, and also underlining the text when it has focus.

- ~~Answer options within a question have two tab-reachable elements - the `li` itself and the nested `input`.~~
  - ~~Potential solution may be to remove the radio button from the tab order and make sure the `li` is labeled properly for interpretation by screen readers. If removing the radio button from the tab order, use aria roles so the `li`s are treated like radio buttons, and make sure up/down arrow key presses move between options appropriately. The ideal solution is probably to remove the `li` from the tab order and allow the radio buttons to function as the screen reader expects them to.~~
    - This is resolved by removing the nested inputs from the tab order and using a combination of new up/down arrow key listeners and aria roles to recreate the natural behavior of radio groups.
    - Would also be nice if pressing Enter moved focus to the button to submit, rather than forcing users to tab through any remaining answer options and then past the 'Return' button to reach it.
      - We could potentially move focus to the submission button if Enter or Space are pressed on an answer that is selected already, but that may be too great a departure from the usual behavior of radio groups.

- ~~Leaving a question without answering it requires tabbing through all of the possible answers to reach the 'Return' button.~~
  - This is improved by adding a listener for the Escape key that allows users to leave a question immediately.

- ~~Submitting an answer will indicate how many unanswered questions remain and will indicate whether the answer just submitted was correct or incorrect, but there is no way of reaching an element on the page at will which would indicate the current score or how many questions remain unanswered.~~
  - Explicitly setting the questions remaining/current score element's tab index to 0 allows it to be reached naturally. ~~This seems to incur a new (possibly non-issue?) issue: since the score element is within the header, the header's text content is always read out after the score element's content is read out.~~
    - This is resolved by making both the h1 heading element containing the text and the questions remaining element both individually reachable in the tab order, rather than the whole header element itself. This allows the question text to be re-read, and also allows the questions remaining text to be read without also re-reading the widget title every time.

- Pressing the Enter/Return key when the 'Return' button inside a question is focused leaves the current question (expected) and sometimes selects whichever question has focus in the main area (unexpected). Pressing the Space key does not do this.
  - ~~Make sure there aren't redundant KeyUp or KeyPress listeners and that keypress events aren't bubbling further than they have to.~~
  - There might not be anything we can do about this, since the 'click' handler is also activated by the Space and Enter keys. In the case of the Enter key, keeping the key held down seems to fire multiple keypress events whereas with the Space key, there's only one. The issue actually appears to be one 'Enter' keypress triggering the event on the 'Return' button and then, if the key is held down, triggering a second event on the question element in the game board after it receives focus. I'm not sure if it's possible (or worthwhile if so) to revisit the event handling on the game board question elements to only react to a keyup event where there was a corresponding keydown event.
    - Maybe using a keydown event on the question element to 'prime' it for a keyup event? It feels like a bit of an overengineered solution for what is ultimately not a significant problem.

- ~~When submitting an answer, the 'Submit Final Answer' button retains focus but is no longer interactive. The 'Submit Final Answer' button is also no longer reachable with tab after an answer has been submitted.~~
  - ~~Either auto-focus the 'Return' button after submitting an answer, or change the behavior of the 'Submit Final Answer' button after submitting an answer to function like the 'Return' button does. No longer being able to reach it via tab is probably fine in either case.~~
  - Auto-focusing the 'Return' button and modifying the text read by screen readers to 'Press the Space or Enter key to...' rather than 'Tab back to the Return button to...' seems like a smoother experience.

- ~~Audio elements used as media within a question require an additional tab to reach the interactive controls.~~
  - ~~Adjust tab order so that the audio element's parent isn't reachable via tab but the audio element itself is?~~
  - It looks like the `audio` DOM element is receiving focus first, and then subsequent tabs move through the interactive controls so there may not be anything we can do about this behavior except add some kind of visual indicator when the audio element (or any of its controls) have focus, so sighted keyboard users know what's going on.
    - Of course, the audio controls look different for every browser so there's only so much we can do to try standardizing the appearance when they have focus.

- ~~Images used as media within a question require an additional tab to reach the 'expand' button. Once an image has been expanded the 'collapse' button is not reachable in the tab order.~~ Images used as media allow for optional image descriptions, which are rendered separately in an adjacent span but are not used as alt text.
  - ~~Adjust tab order so that the expand button's parent isn't reachable via tab but the button itself is? For the purpose of screen readers, the image itself should probably be reachable as well. The 'close' button should at the very least be in the tab order, but it should probably also receive focus automatically after the expand button is activated.~~
  - Removing the parent div from the tab order and adding the image itself to the tab order makes a bit more sense, also adding a visual effect to indicate when the image is focused to help sighted keyboard users.
    - A combination of setting 'inert' on the non-lightbox parts of the question popup when media is expanded, auto-focusing the image/video/whatever with a directive, adjusting tab indices and adding visual indicators for focus should hopefully resolve any other lingering keyboard navigation difficulties. Also auto-focusing the question text after closing the lightbox.
  - The missing alt text may be tricky, since it's kind of on the widget authors to provide it and it could potentially be different from the 'description' text which is already optional. We could potentially add a second input for alt text in the creator and mark the question as incomplete/erroneous if alt text isn't provided.

- ~~Numerous things visible on the page can be reached in the tab order but have no visual indicator that they are currently the element of focus.~~
  - This is easy enough to solve by adding a glow effect using a centered box shadow to the score wheel and category heading elements when they receive focus. The same effect can be added to the widget title using a text shadow.

- It would be nice to be able to move around the game board more freely. Currently the only way to navigate the game board with a keyboard is to tab through all of the questions left to right top to bottom in order, ~~and if any questions were skipped returning to the top requires shift-tabbing backwards through every question and category heading~~.
  - Add listeners to the game board itself for the arrow keys, allow arrow keys to move focus to the appropriate question.
    - It may be necessary to read out instructions per element as to what the arrow keys will do, but that may also be overkill?
  - A button can be rendered after the list of categories which has no width or height and is not visible until it is given focus, meaning it can only be interacted with specifically by tabbing to it. This button's space/enter keypress/click behavior can move focus back to the top of the game board as if it had been tabbed into from the score indicator normally. It may make sense to place an equivalent button at the 'top' of the game board, before any categories are rendered, that moves focus to bottom of the game board - either all the way to the bottom-rightmost question or only to the bottommost category heading.

### PR DESCRIPTION
**Pull request by FrenjaminBanklin**
Closes #41.

Made keyboard instructions button reachable in tab order, pressing space/enter while focused on button will open a dialog for sighted users, button itself is aria-labeled with instructions for unsighted users.

Added new rules for applying 'inert' to all relevant elements on the page for better control over tab order when questions are selected/instructions are visible/etc.

Added question text to tab order so unsighted users can reach it to read again.

Simplified tab order for answer options so that each option is only a single stop in the order instead of two.

Added a listener for the 'Escape' key to the question dialog so it's easier to exit.

Added score wheel/questions remaining element to tab order and adjusted layout of elements to prevent extraneous readings of the widget title.

Adjusted behavior when submitting answers to auto-focus the 'Return' button instead of expecting users to do it.

Added visual effects to most elements on the page to indicate when they have focus so sighted keyboard users can tell where they are.

Added an invisible-until-focused element to the game board to move focus from the bottom back to the top so keyboard users don't have to tab back through the whole list.

Added possible alt text to images - if an image has a description, that description is provided as alt text, if not a reasonable default value is used instead.

**Additional fixes following review:**

Adjusted styles on answered questions so that hovering over them does not produce any effect, but focusing them with tab will still enlarge the element so sighted keyboard users know where they are.

Added a document-level keyboard listener to handle pressing the 'S' or 'Q' key. Pressing the 'S' key will immediately read the current score and number of questions remaining. Pressing the 'Q' key will immediately select the earliest unanswered question if the keyboard instructions are not visible, a question is not currently selected, and all questions have not already been answered.

Fixed the 'Submit Final Answer' button not being reachable in the tab order after opening a lightbox in a question.

**Additional fixes following additional review.**

Added a key bind (W) to the main view to read out which question was last 'visited', essentially to remind non-sighted users of their current location on the game board.

Added a key bind  (S) to read out the current score/number of questions remaining to be answered.

Added a key bind (H) to repeat the keyboard instructions.

Made the keyboard instructions link permanently visible.

Adjusted styling of the keyboard instructions element to be a bit more readable.

Relocated and consolidated aria labels to remove unnecessary tab stops.

Added a separate and distinct list of keyboard instructions when a question is selected. An always-visible element on the screen replaces the question title as the auto-focus target when a question is selected but otherwise functions the same as the keyboard instructions at the game board level, reading both the question title and question-specific keyboard instructions to aria.

Added several new key binds when a question is selected:
 - Q: Reads the question text.
 - S: Moves focus to the 'Submit Final Answer' button.
 - H: Re-reads keyboard instructions.
 - Up Arrow: Selects the last answer option.
 - Down Arrow: Selects the first answer option.

Adjusted existing answer item key binds so key presses for the new question-level key binds are allowed to bubble up.

**Additional additional fixes following additional additional review.**

Added a `tabindex` and a key-up event handler to `audio` elements to make them more reachable and closer to standard for keyboard interaction across browsers.

Wrote in new logic to manually adjust the `innerHTML` of the aria-live region on the page rather than relying on Angular since apparently Firefox would only recognize the first change to that element and all subsequent changes would be ignored.

### CODE REVIEW

**Comment by cayb0rg** [comment]
Love the ease and feel of this. Keyboard accessibility and VoiceOver accessibility are on point. Just some minor things I noticed:
* Not sure what the best practice is about giving non-interactive elements tab indices. I really like the highlighting effects but I’m expecting something to happen when I hit Enter/Space.
* I'm unable to tab to “Submit Final Answer” after opening the image lightbox (still clickable tho). Reopening the image lightbox will fix it. 
* Completed questions appear to still be tabbable with no focus indicator.
* A button to announce the number of questions remaining could be useful, instead of having to navigate to the beginning. Also, this may be an edge case, _but_ in the case where an unsighted user gets lost, a button to go to the next unanswered question would save them from having to look for it.

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
- I'm still iffy on whether non-interactive elements should be part of the tab index, even if they contain important game information. If there's another way of making that information visible to the screenreader, I'm open to alternatives. This is sort of an open question though. One alternative might be to add an `aria-labelledby` or `aria-describedby` attribute to the game board that references the widget title banner text or score dial.
- The keyboard instructions button being invisible until tabbed doesn't sit well with me. I'd rather it be visible by default, and provide visible instructions in addition to the readback provided to screenreaders, since the information is pertinent to sighted keyboard users too.
- Even though the individual answer options occupy a single tab index, screenreaders appear to think the group they're within contains two elements for each answer option. So answer 1 might be "1 of 8" but answer 2 is "3 of 8" and so on. It makes me wonder if there are additional answer options that aren't visible but should be, which isn't actually the case.
- Answer options should indicate if they're a currently selected choice.
- I appreciate that I get audio feedback when an answer is selected, but I should also receive audio feedback on my selection when selecting "Submit Final Answer", since I already receive visual feedback of whether or not my choice was correct.

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
This rules. It's really fast, information is concise and explicit. The only two remaining issues I'm noticing:

1. I receive the live region update indicating I've selected an answer, but when I select `Select Final Answer`, I don't receive any feedback as to whether the choice was correct or not. I have to paginate backwards to the question in the grid to determine whether it was correct.
2. Audio keyboard control is a little wonky cross-browser. In Chrome I can paginate to individual controls and interact with them correctly. In Firefox I can paginate to the individual controls but `enter` and `space` don't do anything; I can only use the arrow keys to control things like the scrubbing the playback and the volume level. Safari doesn't appear to allow any sort of tabbed control of individual elements, I can't interact with it at all.

I don't consider #2 a show-stopper since it's likely an issue that could affect all widgets that make use of embedded audio. But if there's an easy fix, perhaps it can be incorporated here, since it _does_ affect keyboard control.

**Review by clpetersonucf — APPROVED** [review]
15/10. No notes. Ship it.

**Pull request merged**
