### PR TITLE
Style and accessibility tweaks

### PR DESCRIPTION
**Pull request by clpetersonucf**
While updating the accessibility metadata I ran through a small polish pass for various bits of the Enigma player:

- Tweaked focus styles for several elements
- Several adjustments to lightbox layout and formatting. Removed the zoom in/out option. It caused a lot of confusion WRT accessibility, and adjustments to lightbox styling means images should occupy up to nearly the full size of the lightbox, if they're large enough.
- Some not-insignificant accessibility changes to reduce confusion and redundancy, including the lightbox change above and focus of the expand media button for questions. Removed the `tabindex` for images in both the lightbox and question view, and tied descriptions to the focusable elements associated with expanding/closing the lightbox.
- Added alt text descriptions to the `demo.json`
- Added requested tutorial dialog in player
- Updated to MWDK v3.0.0 🎉 

The goal wasn't to overhaul the existing accessibility implementation, just reduce some redundancy and clean up certain behaviors a bit.

### CODE REVIEW

**Review by FrenjaminBanklin — CHANGES_REQUESTED** [review]
Cleaning up the tab order for embedded media in questions is real nice. Everything's working well.

Two minor things - I would probably have the `aria-label` for the button that closes the tutorial read out the text of the tutorial window, since currently all screen readers get is 'close the tutorial'.

I would also probably auto-focus the keyboard instructions button after closing the tutorial, since that is historically the first thing that receives focus when tabbing into the widget frame.

Otherwise, looks good.

**Comment by dmols** [comment]
The changes look good but I'm encountering an issue with the VO; unsure if it's normal for it to be doing this. When I cycle through the tab sequence, the main menu elements are the ones being seen by the VO, and not the screen that _should_ be read. Plays out like this: 

Screenshot 2023-10-30 at 1 50 09 PM

**Comment by dmols** [comment]
Recent commit fixed the issue I was having before and that's the only one I've encountered. Looks good to go. Great work!

**Review by dmols — CHANGES_REQUESTED** [review]
As mentioned before, my issue was fixed with the most recent commit. However, after going through the widget one last time, I do agree with Brandon's suggestions, seeing as being read the tutorial text would be useful for non-sighted users. The auto-focus on the keyboard instructions would also be a good addition, especially since it auto-focuses on a non-clickable button, and this could be rather confusing for users. 

Asides those two things, I believe the widget is very close to being ready for production!

**Review by cayb0rg — APPROVED** [review]
This looks good to me. Only other thing I'd suggest is to preface the keyboard instructions with "Keyboard Instructions" after the question part is read, on the "Show Keyboard Instructions" button inside individual questions.

**Review by FrenjaminBanklin — APPROVED** [review]
I concur with Cay's suggestion, as it would be consistent with how the other keyboard instructions are read.

Otherwise, this looks ready to go.

**Review by dmols — APPROVED** [review]
I do agree that having the label include "Keyboard Instructions" might be a good addition, especially because the text sort of blends together after the question description ends. I would suggest also maybe a small pause between the question is read and the keyboard instructions, though I'm not sure if that's entirely possible. 

Change isn't entirely necessary though, widget looks good to go!

**Pull request merged**
